### ISSUE TITLE
Ask from child process to parent for extra info.

### ISSUE THREAD

**Issue by Strate** [ohjames/process-pool#2]
Is there any way to ask from worker function to parent process for extra data?

**Comment by ohjames** [comment]
I'd combine process pool with an FRP library for this.

**Comment by Strate** [comment]
How it can be achieved? I need to send a message to parent process, how to do that?

**Comment by ohjames** [comment]
There's many ways to achieve it, it's beyond the scope of what process-pool aims to do though. It might not even be acheivable by a wrapper.

**Comment by Strate** [comment]
Sorry for my importunity, but I still need some info.
Intercommunicating between processes done with `process.on` and `process.send` functions. i can send a message from child to a parent via `process.send`. But how can I anwser from parent process to child? I need an instanceof of `ChildProcess`, how can I obtain it?

**Comment by Strate** [comment]
So, trying to `process.send` inside worker function causes to propagate message payload as function result. Seems that it is impossible to send custom message to parent process. Bad for sigh perspective.

**Comment by ohjames** [comment]
`process.send` is synchronous, maybe you could pass the name of a named pipe instead.
